on: push
name: Build and Generate Android Apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building APK
        uses: fahimshahrierrasel/Xamarin-Droid-Builder@1.0.2
        with:
           SOLUTION_NAME: ${{secrets.SOLUTION_NAME}}
           ANDROID_PROJECT_NAME: ${{secrets.ANDROID_PROJECT_NAME}}
