name: CI on Push and Pull Request

on: [push, pull_request]

jobs:

  Android:
    runs-on: macos-latest
    steps:

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd ExemploXamarinGithubActions.Android
        msbuild ExemploXamarinGithubActions.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
          
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd  ExemploXamarinGithubActions.iOS
        nuget restore
        msbuild ExemploXamarinGithubActions.iOS/ExemploXamarinGithubActions.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
